### ISSUE TITLE
Edited - Reading tuning from DATA files as XML

### ISSUE THREAD

**Issue by KhArtNJava** [pboxx/Sims4Tools#23]
Hello.

I found an interesting program, that converts DATA objects to XML files - http://modthesims.info/d/563256 . This program comes with sources, so you can dig into this.

For example, that program could extract file S4_62E94D38_00000009_E23BB17404760CF9%%+_XML.xml ( 
[S4_62E94D38_00000009_E23BB17404760CF9%%+_XML.zip](https://github.com/s4ptacle/Sims4Tools/files/1131941/S4_62E94D38_00000009_E23BB17404760CF9._XML.zip)
 ) with code
`Dim binaryTuning As clsBinaryTuningConvertor = New clsBinaryTuningConvertor(f, "c:\Temp\S4_62E94D38_00000009_E23BB17404760CF9%%+_XML.bnry", "c:\Temp\", False, False)`
where S4_62E94D38_00000009_E23BB17404760CF9%%+_XML.bnry is exported with S4PE file ( 
[S4_62E94D38_00000009_E23BB17404760CF9%%+_XML.zip](https://github.com/s4ptacle/Sims4Tools/files/1131957/S4_62E94D38_00000009_E23BB17404760CF9._XML.zip)
 ) from file c:\Program Files (x86)\Origin Games\The Sims 4\Delta\EP02\SimulationDeltaBuild0.package .

Can you port that code from extractor to S4PE to export not only S4_62E94D38_00000009_E23BB17404760CF9%%+_XML.bnry , to export XML text from it?

**Comment by cmarNYC** [comment]
I've had this in mind for quite some time, both to extract the CAS tuning without needing to do new releases for patches and to extract xml from data files, but haven't had the time to examine and understand Scumbumbo's code yet especially since I don't use Visual Basic. I'll get to it eventually.
