### ISSUE TITLE
Please stop automatic update check on startup.

### ISSUE THREAD

**Issue by s4peuser** [pboxx/Sims4Tools#24]
s4pe V0.5.2-beta
Settings > Automatic update check is already turned off.

Sometimes, when I open s4pe, it shows "unable to connect" message with red "X".
Why does this software connect to internet? Like I mentioned above, automatic update should not happen.
I monitor this github releases so I don't need it.

Can you stop s4pe's startup connection?

**Comment by cmarNYC** [comment]
I found the problem and corrected it - if it tests out the correction will be in the next version.
