### ISSUE TITLE
Wrong version number in released 0.4.8 version.

### ISSUE THREAD

**Issue by KhArtNJava** [pboxx/Sims4Tools#8]
Hello.

I've downloaded https://github.com/s4ptacle/Sims4Tools/releases/tag/v0.4.8-beta and I see this:
![default](https://cloud.githubusercontent.com/assets/757085/22062881/0ebbfb6e-dd8d-11e6-87b9-64ddb13ceeed.png)

**Comment by cmarNYC** [comment]
Thanks, I will look into this.
