### ISSUE TITLE
ClipEventEffect not working

### ISSUE THREAD

**Issue by TURBODRIVER** [pboxx/Sims4Tools#9]
Attempt to add a ClipEventEffect to a CLIP will always result in an error and view of a CLIP that contains a ClipEventEffect event throws an exception as well. There is no way to look up, edit or add effect events to CLIPs in the current develop release (0.4.8 beta) and older versions.

**Comment by cmarNYC** [comment]
This will be fixed in the next version. Meanwhile a test fixed version will be posted shortly on MTS: http://www.modthesims.info/showthread.php?goto=lastpost&t=581232
